import 'package:flutter/material.dart';

ThemeData themeData = ThemeData(
  colorScheme: ColorScheme.fromSeed(seedColor: const Color(0x0F16161E)),
  backgroundColor: const Color(0x0F16161E),
  useMaterial3: true,
// COLOR
  // [colorScheme] is the preferred way to configure colors. The other color
  // properties (as well as primaryColorBrightness, and primarySwatch)
  // will gradually be phased out, see https://github.com/flutter/flutter/issues/91772.

// Brightness? brightness,
// Color? canvasColor,
// Color? cardColor,
// ColorScheme? colorScheme,
// Color? colorSchemeSeed,
// Color? dialogBackgroundColor,
// Color? disabledColor,
// Color? dividerColor,
// Color? focusColor,
// Color? highlightColor,
// Color? hintColor,
// Color? hoverColor,
// Color? indicatorColor,
// Color? primaryColor,
// Color? primaryColorDark,
// Color? primaryColorLight,
// MaterialColor? primarySwatch,
// Color? scaffoldBackgroundColor,
// Color? secondaryHeaderColor,
// Color? shadowColor,
// Color? splashColor,
// Color? unselectedWidgetColor,
// // TYPOGRAPHY & ICONOGRAPHY
// String? fontFamily,
// List<String>? fontFamilyFallback,
// String? package,
// IconThemeData? iconTheme,
// IconThemeData? primaryIconTheme,
// TextTheme? primaryTextTheme,
// TextTheme? textTheme,
// Typography? typography,
// // COMPONENT THEMES
// ActionIconThemeData? actionIconTheme,
// AppBarTheme? appBarTheme,
// BadgeThemeData? badgeTheme,
// MaterialBannerThemeData? bannerTheme,
// BottomAppBarTheme? bottomAppBarTheme,
// BottomNavigationBarThemeData? bottomNavigationBarTheme,
// BottomSheetThemeData? bottomSheetTheme,
// ButtonBarThemeData? buttonBarTheme,
// ButtonThemeData? buttonTheme,
// CardTheme? cardTheme,
// CheckboxThemeData? checkboxTheme,
// ChipThemeData? chipTheme,
// DataTableThemeData? dataTableTheme,
// DatePickerThemeData? datePickerTheme,
// DialogTheme? dialogTheme,
// DividerThemeData? dividerTheme,
// DrawerThemeData? drawerTheme,
// DropdownMenuThemeData? dropdownMenuTheme,
// ElevatedButtonThemeData? elevatedButtonTheme,
// ExpansionTileThemeData? expansionTileTheme,
// FilledButtonThemeData? filledButtonTheme,
// FloatingActionButtonThemeData? floatingActionButtonTheme,
// IconButtonThemeData? iconButtonTheme,
// ListTileThemeData? listTileTheme,
// MenuBarThemeData? menuBarTheme,
// MenuButtonThemeData? menuButtonTheme,
// MenuThemeData? menuTheme,
// NavigationBarThemeData? navigationBarTheme,
// NavigationDrawerThemeData? navigationDrawerTheme,
// NavigationRailThemeData? navigationRailTheme,
// OutlinedButtonThemeData? outlinedButtonTheme,
// PopupMenuThemeData? popupMenuTheme,
// ProgressIndicatorThemeData? progressIndicatorTheme,
// RadioThemeData? radioTheme,
// SearchBarThemeData? searchBarTheme,
// SearchViewThemeData? searchViewTheme,
// SegmentedButtonThemeData? segmentedButtonTheme,
// SliderThemeData? sliderTheme,
// SnackBarThemeData? snackBarTheme,
// SwitchThemeData? switchTheme,
// TabBarTheme? tabBarTheme,
// TextButtonThemeData? textButtonTheme,
// TextSelectionThemeData? textSelectionTheme,
// TimePickerThemeData? timePickerTheme,
// ToggleButtonsThemeData? toggleButtonsTheme,
// TooltipThemeData? tooltipTheme,
);
